#pragma once

//halcon nodes
#include "halcon/HImageLoaderModel.hpp"
#include "halcon/HImageFolderModel.hpp"
#include "halcon/HImageShowModel.hpp"
#include "halcon/HImageRGB2GrayModel.hpp"
#include "halcon/HImageThresholdModel.hpp"
#include "halcon/HImageSplitChanelModel.hpp"
#include "halcon/HRegionSelectModel.hpp"
#include "halcon/HRegionConnectModel.hpp"
#include "halcon/HRegionShapeTransModel.hpp"
#include "halcon/HImageReduceDomainModel.hpp"
#include "halcon/HRegionFillUpShapeModel.hpp"
#include "halcon/HRegionOpenCircleModel.hpp"
#include "halcon/HRegionUnionModel.hpp"
#include "halcon/HRegionDifferenceModel.hpp"
#include "halcon/HRegionSelectShapeStdModel.hpp"
#include "halcon/HImageDLSegmentModel.hpp"
